/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlightsIndexRouteImport } from './routes/flights.index'
import { Route as FlightsIdRouteImport } from './routes/flights.$id'

const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsIndexRoute = FlightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlightsRoute,
} as any)
const FlightsIdRoute = FlightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FlightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flights': typeof FlightsRouteWithChildren
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/flights/$id': typeof FlightsIdRoute
  '/flights/': typeof FlightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/flights/$id': typeof FlightsIdRoute
  '/flights': typeof FlightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flights': typeof FlightsRouteWithChildren
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/flights/$id': typeof FlightsIdRoute
  '/flights/': typeof FlightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/flights'
    | '/login'
    | '/personal'
    | '/flights/$id'
    | '/flights/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/personal' | '/flights/$id' | '/flights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/flights'
    | '/login'
    | '/personal'
    | '/flights/$id'
    | '/flights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FlightsRoute: typeof FlightsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PersonalRoute: typeof PersonalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/': {
      id: '/flights/'
      path: '/'
      fullPath: '/flights/'
      preLoaderRoute: typeof FlightsIndexRouteImport
      parentRoute: typeof FlightsRoute
    }
    '/flights/$id': {
      id: '/flights/$id'
      path: '/$id'
      fullPath: '/flights/$id'
      preLoaderRoute: typeof FlightsIdRouteImport
      parentRoute: typeof FlightsRoute
    }
  }
}

interface FlightsRouteChildren {
  FlightsIdRoute: typeof FlightsIdRoute
  FlightsIndexRoute: typeof FlightsIndexRoute
}

const FlightsRouteChildren: FlightsRouteChildren = {
  FlightsIdRoute: FlightsIdRoute,
  FlightsIndexRoute: FlightsIndexRoute,
}

const FlightsRouteWithChildren =
  FlightsRoute._addFileChildren(FlightsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FlightsRoute: FlightsRouteWithChildren,
  LoginRoute: LoginRoute,
  PersonalRoute: PersonalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
